from dotenv import load_dotenv
import os

load_dotenv()

TELEGRAM_API_ID = int(os.getenv("TELEGRAM_API_ID"))
TELEGRAM_API_HASH = os.getenv("TELEGRAM_API_HASH")
TELEGRAM_PHONE_NUMBER = os.getenv("TELEGRAM_PHONE_NUMBER")
PALACENFT_X_USER_DATA = os.getenv("PALACENFT_X_USER_DATA")
PALACENFT_BOT = os.getenv("PALACENFT_BOT")
TELEGRAM_SESSION_NAME = os.getenv("TELEGRAM_SESSION_NAME")
PALACENFT_BASE_URL = os.getenv("PALACENFT_BASE_URL")
REQUEST_TIMEOUT = int(os.getenv("REQUEST_TIMEOUT"))
TELEGRAM_SESSION_LOGIN_TIMEOUT = int(os.getenv("TELEGRAM_SESSION_LOGIN_TIMEOUT"))
COLLECTION_REQUEST_DELAY = float(os.getenv("COLLECTION_REQUEST_DELAY"))
COLLECTIONS_UPDATE_INTERVAL = int(os.getenv("COLLECTIONS_UPDATE_INTERVAL"))
ASYNC_DATABASE_URL = os.getenv("ASYNC_DATABASE_URL")
